version: '3.3'
services:
  minio_mc:
    image: minio/mc:RELEASE.2021-11-05T10-05-06Z
    external_links:
      - duckdb-minio_minio_1:duckdb-minio
    networks:
      duckdb-minio_duckdb_network:
    entrypoint: >
      /bin/sh -c "
        while true; do
          /usr/bin/mc config host add myminio http://duckdb-minio.com:9000 duckdb_minio_admin duckdb_minio_admin_password
          if [ $$? -eq 0 ]; then
            break
          fi
          echo 'Failed to add host alias, trying again in a second'
          sleep 1
        done

        /usr/bin/mc share download myminio/test-bucket/presigned/web_page.csv
        /usr/bin/mc share download myminio/test-bucket/presigned/web_page.parquet

        /usr/bin/mc share download myminio/test-bucket/presigned/lineitem_large.parquet
      "
networks:
  duckdb-minio_duckdb_network:
    external: true