name: Swift
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'test/**'
      - 'tools/juliapkg/**'
      - 'tools/nodejs/**'
      - 'tools/pythonpkg/**'
      - 'tools/rpkg/**'
      - '.github/workflows/**'
      - '!.github/workflows/Swift.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

jobs:

  test-apple-platforms:
    strategy:
      matrix:
        # destinations need to match selected version of Xcode
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#installed-simulators
        destination:
          - 'macOS'
          - 'iOS Simulator,name=iPhone 14'
          - 'watchOS Simulator,name=Apple Watch Ultra (49mm)'
          - 'tvOS Simulator,name=Apple TV 4K (at 1080p) (2nd generation)'
    runs-on: macos-12
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Package
        run: python3 tools/swiftpm/create_package.py tools/swiftpm

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app && /usr/bin/xcodebuild -version

      - name: Run Tests
        run: |
          xcrun xcodebuild test \
            -workspace tools/swiftpm/duckdb-swift/DuckDB.xcworkspace \
            -scheme DuckDB \
            -destination platform='${{ matrix.destination }}'
          
